name: Build & Package
run-name: Build & Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm' # See 'Options' for all available distributions
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: ./mvnw clean install
