name: Build & Package
run-name: Build & Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm' # See 'Options' for all available distributions
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Versioning
      id: versioning
      run: |
        VERSION=$(date +"%d%m%Y%H%M")
        echo ::set-output name=version::$VERSION

    - name: Build with Maven
      run: |
        ./mvnw -B spring-boot:build-image \
          -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:${{ steps.versioning.outputs.version }}

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker image ls
        docker push ghcr.io/${{ github.repository }}:${{ steps.versioning.outputs.version }}
